spring:
  datasource:
    url: ${datasource-url}  
    username: ${datasource-username}   #url of mysql in railway
    password: ${datasource-password}   #password of mysql in railway
  jpa:
    hibernate:
      ddl-auto: none #Turning off ddl auto generation

ai:
geminiai:
  endpoint: ${AI_GEMINIAI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}
  api-key: ${AI_GEMINIAI_API_KEY:YOUR_API_KEY}