spring:
  datasource:
    url: jdbc:h2:mem:hogwarts   
    username: sa
    password:
    driver-class-name: org.h2.Driver
ai:
 geminiai:
  endpoint: ${AI_GEMINIAI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}
  api-key: ${AI_GEMINIAI_API_KEY:YOUR_API_KEY}